name = "theme2rage"
license = "MIT"
licenselink = "https://github.com/2rage/personal-site/master/LICENSE.md"
description = "A simple theme for Hugo"
homepage = "https://2rage.com/"

tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.79.0"

[author]
name = "Konstantin Yakovlev"
homepage = "https://2rage.com"
